name: Label Commands
description: Perform commands when issues or pull requests are labeled or unlabeled.
author: bubkoo <bubkoo.wy@gmail.com>
inputs:
  GITHUB_TOKEN:
    description: Your GitHub token for authentication
    required: true
  CONFIG_FILE:
    description: Config file path relative to your repo's root.
    required: false
runs:
  using: node16
  main: dist/index.js
branding:
  icon: command
  color: yellow # gray-dark purple red orange green blue yellow black white
